### ISSUE TITLE
Pull request with Promise Fixes

### ISSUE THREAD

**Issue by Johanndutoit** [passmarked/browser#2]
See @tvpavan created a fork with a few fixes for promises. @tvpavan would love to merge that into our main branch, could you elaborate what issues you encountered?

Going to be picking this up to get it live running on our systems as well so welcome to the ride :)

See https://github.com/minewhat/browser

**Comment by Johanndutoit** [comment]
Merged in fixes on my own for now.

**Comment by tvpavan** [comment]
Oh Nice! . When i tested it the promises flow was not fully functional to my need hence the fix. You are free to merge back to main.
